language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - "mkdir ~/.composer && echo '{\"config\":{\"github-oauth\": {\"github.com\":\"fa354b2f030836334eac842f8fd69a03e353d247\"}}}' > ~/.composer/config.json"
    - "composer install --dev --no-progress --no-custom-installers --no-scripts"
